### ISSUE TITLE
Squid Cache for all sites that make sense

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/deployment-configs#141]
We need a Squid reverse-proxy cache in front of, at least:

- snapcraft.io
- blog.ubuntu.com
- tutorials.ubuntu.com
- usn.ubuntu.com
- www.canonical.com (when it moves over)
- www.ubuntu.com (when it moves over)

But for this epic we'll just worry about getting squid set up:

- [ ] Get a squid installation set up
- [ ] Confirm the ideal Squid configuration for our sites
- [ ] Apply the ideal configuration to our Squid installation

**Comment by nottrobin** [comment]
This is blocked until https://portal.admin.canonical.com/C109653 is completed.

This may also be ultimately made redundant for our purposes by the introduction of a CMS in front of all sites, instead of the Squid cache. However, this roll-out will take quite a while, so it's probably still worth setting up Squid in the interim.

**Comment by tbille** [comment]
content cache is fixing that.
